-- Sample Project Overview Data for Testing
-- Generated for Fridays at Four project_overview table

-- Existing row (Creative Writing Project 2)
INSERT INTO "public"."project_overview" ("id", "user_id", "project_name", "project_type", "description", "current_phase", "goals", "challenges", "success_metrics", "creation_date", "last_updated", "timeline", "weekly_commitment", "resources_needed", "working_style") VALUES ('8676a6db-1541-4fb5-90b9-dd127a69c5eb', '48a49ff5-0cf5-434c-b5c7-ac9f01b3bb1e', 'Creative Writing Project 2', 'book', 'A contemporary fiction novel exploring themes of identity and belonging in modern urban settings. The story follows multiple interconnected characters as they navigate life transitions and discover unexpected connections.', 'Planning', ARRAY['{"goal":"Complete first draft","description":"Write 80,000-word first draft within 6 months"}'::jsonb, '{"goal":"Develop authentic characters","description":"Create compelling, multi-dimensional characters with distinct voices"}'::jsonb, '{"goal":"Establish writing routine","description":"Write consistently 5 days per week, 1000 words minimum per session"}'::jsonb], ARRAY['{"challenge":"Time management","description":"Balancing writing with full-time work and family responsibilities"}'::jsonb, '{"challenge":"Maintaining momentum","description":"Staying motivated through difficult middle sections of the novel"}'::jsonb, '{"challenge":"Self-doubt","description":"Overcoming imposter syndrome and perfectionist tendencies"}'::jsonb], '{"quality_metrics": {"prose_quality": "Clean, engaging prose suitable for target audience", "plot_consistency": "No plot holes or contradictions", "character_development": "Each character has clear arc and growth"}, "daily_word_target": 500, "word_count_target": 80000, "success_definition": "Completed first draft ready for beta readers", "completion_timeline": "6 months", "weekly_chapter_goal": 1}', '2025-07-05 08:38:28.43637+00', '2025-07-05 08:38:28.43637+00', '{"phase_1": {"name": "Planning & Outline", "duration": "4 weeks", "deliverables": ["Character profiles", "Plot outline", "Chapter breakdown"]}, "phase_2": {"name": "First Draft", "duration": "20 weeks", "deliverables": ["Complete manuscript", "Chapter-by-chapter completion"]}, "phase_3": {"name": "Initial Review", "duration": "2 weeks", "deliverables": ["Self-edit", "Beta reader preparation"]}}', '10-15 hours per week', '{"budget": "$200 for software and reference materials", "workspace": "Dedicated home office with minimal distractions", "writing_tools": ["Scrivener", "Google Docs for backup"], "support_network": ["Local writing group", "Online writing community"], "research_materials": ["Writing craft books", "Genre research"]}', 'Morning writer - most productive 6-8 AM. Prefers detailed outlines before writing. Works best with accountability partners and regular check-ins.');

-- Sample 1: Photography Portfolio Project
INSERT INTO "public"."project_overview" ("id", "user_id", "project_name", "project_type", "description", "current_phase", "goals", "challenges", "success_metrics", "creation_date", "last_updated", "timeline", "weekly_commitment", "resources_needed", "working_style") VALUES 
('f1e2d3c4-b5a6-7890-1234-567890abcdef', '48a49ff5-0cf5-434c-b5c7-ac9f01b3bb1e', 'Urban Stories Photography Series', 'photography', 'A documentary photography series capturing the untold stories of small business owners in my city. Each portrait will be accompanied by a short written story about their journey and dreams.', 'Active', 
ARRAY['{"goal":"Complete 20 portrait sessions","description":"Photograph 20 diverse small business owners with compelling stories"}'::jsonb, '{"goal":"Develop signature style","description":"Create consistent visual aesthetic that captures both vulnerability and strength"}'::jsonb, '{"goal":"Build portfolio website","description":"Launch professional website showcasing the series with integrated stories"}'::jsonb], 
ARRAY['{"challenge":"Subject recruitment","description":"Finding willing participants who are comfortable being photographed"}'::jsonb, '{"challenge":"Technical consistency","description":"Maintaining lighting and composition quality across different locations"}'::jsonb, '{"challenge":"Story extraction","description":"Getting subjects to open up and share meaningful personal narratives"}'::jsonb], 
'{"portfolio_size": 20, "website_launch": "3 months", "social_media_engagement": "1000+ followers", "exhibition_goal": "Local gallery showing", "story_quality": "Each portrait paired with 300-500 word narrative"}', 
'2025-01-15 09:22:15.123456+00', '2025-01-15 09:22:15.123456+00', 
'{"phase_1": {"name": "Planning & Equipment", "duration": "2 weeks", "deliverables": ["Shot list", "Equipment check", "Location scouting"]}, "phase_2": {"name": "Photography Sessions", "duration": "10 weeks", "deliverables": ["20 completed sessions", "Raw photo editing"]}, "phase_3": {"name": "Website & Launch", "duration": "4 weeks", "deliverables": ["Portfolio website", "Social media launch", "Gallery submission"]}}', 
'8-12 hours per week', 
'{"budget": "$500 for website and printing", "equipment": ["DSLR camera", "Portable lighting kit", "Laptop for editing"], "software": ["Lightroom", "Photoshop", "Squarespace"], "transportation": "Car for location visits"}', 
'Weekend warrior - prefers concentrated work sessions. Thrives on human connection and storytelling. Works best with flexible scheduling around subjects availability.');

-- Sample 2: Podcast Launch Project  
INSERT INTO "public"."project_overview" ("id", "user_id", "project_name", "project_type", "description", "current_phase", "goals", "challenges", "success_metrics", "creation_date", "last_updated", "timeline", "weekly_commitment", "resources_needed", "working_style") VALUES 
('a9b8c7d6-e5f4-3210-9876-543210fedcba', '48a49ff5-0cf5-434c-b5c7-ac9f01b3bb1e', 'The Creative Pivot Podcast', 'podcast', 'A bi-weekly interview podcast featuring people who made major career changes to pursue their creative passions. Each episode explores the practical and emotional journey of creative pivoting.', 'Planning', 
ARRAY['{"goal":"Launch with 8 episodes","description":"Record and publish first season of 8 high-quality episodes"}'::jsonb, '{"goal":"Build audience base","description":"Reach 500 downloads per episode by end of first season"}'::jsonb, '{"goal":"Establish interview skills","description":"Develop confident, engaging interview style that draws out compelling stories"}'::jsonb], 
ARRAY['{"challenge":"Guest booking","description":"Finding and scheduling interesting guests with compelling pivot stories"}'::jsonb, '{"challenge":"Technical quality","description":"Learning audio editing and maintaining professional sound quality"}'::jsonb, '{"challenge":"Consistent publishing","description":"Maintaining bi-weekly schedule while managing full-time job"}'::jsonb], 
'{"episode_count": 8, "download_target": 500, "guest_diversity": "50% career changers, 50% creative entrepreneurs", "audio_quality": "Professional broadcast standard", "audience_engagement": "Active social media community"}', 
'2025-01-20 14:30:45.789012+00', '2025-01-20 14:30:45.789012+00', 
'{"phase_1": {"name": "Setup & Planning", "duration": "3 weeks", "deliverables": ["Podcast concept refinement", "Recording setup", "Guest outreach list"]}, "phase_2": {"name": "Recording Season 1", "duration": "8 weeks", "deliverables": ["8 recorded episodes", "Consistent publishing schedule"]}, "phase_3": {"name": "Growth & Refinement", "duration": "4 weeks", "deliverables": ["Audience feedback analysis", "Season 2 planning"]}}', 
'6-10 hours per week', 
'{"budget": "$300 for microphone and hosting", "equipment": ["USB microphone", "Headphones", "Laptop"], "software": ["Audacity", "Spotify for Podcasters"], "subscriptions": ["Podcast hosting service"]}', 
'Evening focused - records after work hours. Prefers batch recording sessions. Energized by deep conversations and human stories.');

-- Sample 3: Art Installation Project
INSERT INTO "public"."project_overview" ("id", "user_id", "project_name", "project_type", "description", "current_phase", "goals", "challenges", "success_metrics", "creation_date", "last_updated", "timeline", "weekly_commitment", "resources_needed", "working_style") VALUES 
('1a2b3c4d-5e6f-7890-abcd-ef1234567890', '48a49ff5-0cf5-434c-b5c7-ac9f01b3bb1e', 'Memory Garden Installation', 'art', 'An interactive outdoor art installation using recycled materials to create a space for community reflection and memory sharing. Visitors can leave written memories that become part of the evolving artwork.', 'Active', 
ARRAY['{"goal":"Complete installation design","description":"Finalize architectural plans and material specifications for 20x15 foot installation"}'::jsonb, '{"goal":"Secure exhibition space","description":"Partner with local park or community center for 6-month display"}'::jsonb, '{"goal":"Engage community participation","description":"Create system for visitors to safely contribute written memories to the installation"}'::jsonb], 
ARRAY['{"challenge":"Weather resistance","description":"Ensuring materials and memory collection system withstand outdoor conditions"}'::jsonb, '{"challenge":"Permits and regulations","description":"Navigating city requirements for temporary public art installations"}'::jsonb, '{"challenge":"Community engagement","description":"Designing intuitive participation method that feels safe and meaningful for diverse visitors"}'::jsonb], 
'{"installation_size": "20x15 feet", "community_contributions": "100+ memory submissions", "exhibition_duration": "6 months", "visitor_engagement": "Daily interaction documented", "media_coverage": "Local arts publication feature"}', 
'2025-02-01 11:15:30.456789+00', '2025-02-01 11:15:30.456789+00', 
'{"phase_1": {"name": "Design & Permits", "duration": "6 weeks", "deliverables": ["Final design plans", "Permit approvals", "Material sourcing"]}, "phase_2": {"name": "Construction", "duration": "4 weeks", "deliverables": ["Installation assembly", "Community launch event"]}, "phase_3": {"name": "Exhibition & Documentation", "duration": "24 weeks", "deliverables": ["Ongoing maintenance", "Community engagement tracking", "Final documentation"]}}', 
'12-18 hours per week', 
'{"budget": "$800 for materials and permits", "materials": ["Recycled wood", "Weather-resistant hardware", "Protective coatings"], "tools": ["Basic construction tools", "Weather monitoring equipment"], "transportation": "Truck rental for material transport"}', 
'Hands-on maker - works best with physical materials. Prefers morning construction work. Inspired by community feedback and collaborative creation.');

-- Sample 4: Children's Book Project
INSERT INTO "public"."project_overview" ("id", "user_id", "project_name", "project_type", "description", "current_phase", "goals", "challenges", "success_metrics", "creation_date", "last_updated", "timeline", "weekly_commitment", "resources_needed", "working_style") VALUES 
('9z8y7x6w-5v4u-3210-fedc-ba9876543210', '48a49ff5-0cf5-434c-b5c7-ac9f01b3bb1e', 'Luna the Library Cat', 'book', 'A picture book series about Luna, a curious library cat who helps children discover the magic of reading. The first book follows Luna as she guides a shy child to find confidence through storytelling.', 'Planning', 
ARRAY['{"goal":"Complete manuscript and illustrations","description":"Finish 32-page picture book with full-color illustrations and engaging text for ages 4-8"}'::jsonb, '{"goal":"Develop Luna character brand","description":"Create consistent character design and personality that can support future books in series"}'::jsonb, '{"goal":"Submit to publishers","description":"Research and submit to 10 appropriate children book publishers or agents"}'::jsonb], 
ARRAY['{"challenge":"Illustration consistency","description":"Maintaining character and style consistency across 16 illustration spreads"}'::jsonb, '{"challenge":"Age-appropriate language","description":"Writing engaging text that hits the right reading level for target age group"}'::jsonb, '{"challenge":"Market competition","description":"Standing out in the crowded children picture book market"}'::jsonb], 
'{"page_count": 32, "illustration_count": 16, "reading_level": "Ages 4-8", "submission_target": 10, "character_development": "Luna series bible completed", "manuscript_quality": "Professional ready for submission"}', 
'2025-01-10 16:45:20.987654+00', '2025-01-10 16:45:20.987654+00', 
'{"phase_1": {"name": "Story Development", "duration": "4 weeks", "deliverables": ["Complete manuscript", "Character style guide", "Page layout sketches"]}, "phase_2": {"name": "Illustration", "duration": "8 weeks", "deliverables": ["16 finished illustrations", "Cover design"]}, "phase_3": {"name": "Publishing Prep", "duration": "3 weeks", "deliverables": ["Publisher research", "Submission materials", "Query letters"]}}', 
'8-12 hours per week', 
'{"budget": "$150 for art supplies and submission costs", "art_supplies": ["Watercolor paints", "Illustration paper", "Digital tablet"], "software": ["Procreate", "Adobe Illustrator"], "reference_materials": ["Children book market guides", "Character development books"]}', 
'Visual storyteller - alternates between writing and illustration sessions. Works best in quiet, inspiring spaces. Motivated by connecting with young readers.');

-- Sample 5: Music Album Project
INSERT INTO "public"."project_overview" ("id", "user_id", "project_name", "project_type", "description", "current_phase", "goals", "challenges", "success_metrics", "creation_date", "last_updated", "timeline", "weekly_commitment", "resources_needed", "working_style") VALUES 
('5a4b3c2d-1e0f-9876-5432-10fedcba9876', '48a49ff5-0cf5-434c-b5c7-ac9f01b3bb1e', 'Midnight Reflections EP', 'music', 'A 5-song indie folk EP exploring themes of late-night introspection and personal growth. Featuring acoustic guitar, subtle electronic elements, and intimate vocals recorded in a home studio setup.', 'Active', 
ARRAY['{"goal":"Complete 5 original songs","description":"Write, arrange, and record 5 songs with professional quality production"}'::jsonb, '{"goal":"Develop signature sound","description":"Blend acoustic folk with modern production techniques to create unique sonic identity"}'::jsonb, '{"goal":"Release and promote","description":"Distribute EP on streaming platforms and build initial fanbase through social media and local performances"}'::jsonb], 
ARRAY['{"challenge":"Home recording quality","description":"Achieving professional sound quality with limited home studio equipment"}'::jsonb, '{"challenge":"Vocal confidence","description":"Overcoming self-consciousness about vocal performance and delivery"}'::jsonb, '{"challenge":"Music promotion","description":"Building audience from zero without marketing budget or industry connections"}'::jsonb], 
'{"song_count": 5, "recording_quality": "Streaming platform ready", "streaming_presence": "Spotify, Apple Music, Bandcamp", "local_performance": "3 live shows booked", "social_media": "500+ engaged followers"}', 
'2025-01-25 20:10:35.135792+00', '2025-01-25 20:10:35.135792+00', 
'{"phase_1": {"name": "Songwriting & Arranging", "duration": "6 weeks", "deliverables": ["5 complete song arrangements", "Demo recordings", "Lyric finalization"]}, "phase_2": {"name": "Recording & Production", "duration": "8 weeks", "deliverables": ["5 finished tracks", "EP mastering"]}, "phase_3": {"name": "Release & Promotion", "duration": "4 weeks", "deliverables": ["Streaming platform distribution", "Social media campaign", "Live performance bookings"]}}', 
'10-15 hours per week', 
'{"budget": "$400 for equipment and distribution", "equipment": ["Audio interface", "Condenser microphone", "Monitor headphones"], "software": ["Logic Pro", "DistroKid for distribution"], "instruments": ["Acoustic guitar", "MIDI keyboard"]}', 
'Night owl musician - most creative after 9 PM. Prefers long, uninterrupted sessions. Inspired by emotional authenticity and sonic experimentation.');

-- Sample 6: Documentary Film Project
INSERT INTO "public"."project_overview" ("id", "user_id", "project_name", "project_type", "description", "current_phase", "goals", "challenges", "success_metrics", "creation_date", "last_updated", "timeline", "weekly_commitment", "resources_needed", "working_style") VALUES 
('7c6b5a49-8d7e-6f5a-4b3c-2d1e0f987654', '48a49ff5-0cf5-434c-b5c7-ac9f01b3bb1e', 'Hometown Heroes', 'film', 'A 30-minute documentary highlighting three local community leaders who are making a difference through grassroots initiatives. The film will premiere at the local film festival and be used to inspire community engagement.', 'Planning', 
ARRAY['{"goal":"Complete 30-minute documentary","description":"Produce professional-quality documentary suitable for film festival submission"}'::jsonb, '{"goal":"Tell compelling human stories","description":"Capture authentic, emotional narratives that inspire viewers to community action"}'::jsonb, '{"goal":"Festival premiere","description":"Successfully submit and screen at local film festival with community impact panel discussion"}'::jsonb], 
ARRAY['{"challenge":"Subject scheduling","description":"Coordinating filming schedules with busy community leaders across multiple locations"}'::jsonb, '{"challenge":"Technical storytelling","description":"Learning advanced video editing and sound design to create professional documentary"}'::jsonb, '{"challenge":"Funding and equipment","description":"Managing project costs while accessing necessary filming and editing equipment"}'::jsonb], 
'{"runtime": "30 minutes", "subject_count": 3, "festival_submission": "Local film festival accepted", "community_impact": "Post-screening discussion panel", "technical_quality": "Broadcast standard video and audio"}', 
'2025-02-05 13:25:40.246801+00', '2025-02-05 13:25:40.246801+00', 
'{"phase_1": {"name": "Pre-Production", "duration": "4 weeks", "deliverables": ["Subject interviews scheduled", "Shot list creation", "Equipment secured"]}, "phase_2": {"name": "Production", "duration": "6 weeks", "deliverables": ["All interviews filmed", "B-roll footage collected"]}, "phase_3": {"name": "Post-Production", "duration": "6 weeks", "deliverables": ["Final cut completed", "Festival submission ready"]}}', 
'12-16 hours per week', 
'{"budget": "$600 for equipment rental and festival fees", "equipment": ["DSLR camera with video capability", "External microphone", "Tripod", "Lighting kit"], "software": ["Final Cut Pro", "Adobe Premiere"], "transportation": "Car for location filming"}', 
'Collaborative storyteller - energized by human connection. Prefers flexible scheduling around subjects. Works best when balancing technical and creative aspects.'); 